/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dom_sax_jaxb;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author aghsk
 */
public class Formulario extends javax.swing.JFrame {

    DOM gesDom = new DOM();
    SAX gesSAX = new SAX();
    JAXB gesJAXB = new JAXB();

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensaje = new javax.swing.JLabel();
        jButtonMostrarDOM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDOM = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAñadir = new javax.swing.JButton();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldPublicado = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTituloAntiguo = new javax.swing.JTextField();
        jTextFieldTituloNuevo = new javax.swing.JTextField();
        jButtonModificarTitulo = new javax.swing.JButton();
        jButtonMostrarSAX = new javax.swing.JButton();
        jButtonMostrarJAXB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jAbrirDOM = new javax.swing.JMenuItem();
        jAbrirSAX = new javax.swing.JMenuItem();
        jAbrirJAXB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMensaje.setText("<Fichero XML no seleccinado>");

        jButtonMostrarDOM.setText("Mostrar Contenido DOM");
        jButtonMostrarDOM.setEnabled(false);
        jButtonMostrarDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDOMActionPerformed(evt);
            }
        });

        jTextAreaDOM.setColumns(20);
        jTextAreaDOM.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDOM);

        jLabel1.setText("Titulo: ");

        jLabel2.setText("Autor: ");

        jLabel3.setText("Publicado en ");

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar DOM como salida XML");
        jButtonGuardar.setEnabled(false);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Titulo Antiguo: ");

        jLabel5.setText("Titulo Nuevo:");

        jButtonModificarTitulo.setText("Modificar");
        jButtonModificarTitulo.setEnabled(false);
        jButtonModificarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTituloActionPerformed(evt);
            }
        });

        jButtonMostrarSAX.setText("Mostrar Contenido SAX");
        jButtonMostrarSAX.setEnabled(false);
        jButtonMostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarSAXActionPerformed(evt);
            }
        });

        jButtonMostrarJAXB.setText("Mostrar Contenido JAXB");
        jButtonMostrarJAXB.setEnabled(false);
        jButtonMostrarJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarJAXBActionPerformed(evt);
            }
        });

        jMenu1.setText("Ficheros XML");

        jAbrirDOM.setText("Abrir DOM");
        jAbrirDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirDOMActionPerformed(evt);
            }
        });
        jMenu1.add(jAbrirDOM);

        jAbrirSAX.setText("Abrir SAX");
        jAbrirSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirSAXActionPerformed(evt);
            }
        });
        jMenu1.add(jAbrirSAX);

        jAbrirJAXB.setText("Abrir JAXB");
        jAbrirJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirJAXBActionPerformed(evt);
            }
        });
        jMenu1.add(jAbrirJAXB);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPublicado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAñadir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButtonMostrarJAXB)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTituloAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButtonGuardar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonModificarTitulo)))
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMostrarDOM)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonMostrarSAX)
                        .addGap(0, 311, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMostrarDOM)
                            .addComponent(jButtonMostrarSAX)
                            .addComponent(jButtonMostrarJAXB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButtonAñadir)
                            .addComponent(jTextFieldPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jButtonGuardar)
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTituloAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarTitulo)))
                .addGap(98, 98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAbrirDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirDOMActionPerformed

        File ficheroXML;
        ficheroXML = dialogoSeleccionarFichero();

        if (ficheroXML == null) {
            jLabelMensaje.setText("Vuelve a seleccionar el fichero.");
        } else {
            if (gesDom.abrir_XML_DOM(ficheroXML) == -1) {
                this.jLabelMensaje.setText("Error al crear el objeto DOM.");
                this.jButtonMostrarDOM.setEnabled(false);
                this.jButtonAñadir.setEnabled(false);
                this.jButtonGuardar.setEnabled(false);
                this.jButtonModificarTitulo.setEnabled(false);
                this.jButtonMostrarSAX.setEnabled(false);
                this.jButtonMostrarJAXB.setEnabled(false);
            } else {
                this.jLabelMensaje.setText("Objeto DOM creado.");
                this.jButtonMostrarDOM.setEnabled(true);
                this.jButtonAñadir.setEnabled(true);
                this.jButtonGuardar.setEnabled(true);
                this.jButtonModificarTitulo.setEnabled(true);
                this.jButtonMostrarSAX.setEnabled(false);
                this.jButtonMostrarJAXB.setEnabled(false);
            }
        }

    }//GEN-LAST:event_jAbrirDOMActionPerformed

    private void jButtonMostrarDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDOMActionPerformed

        String salida = "";
        salida = gesDom.recorrerDOMyMostrar();
        this.jTextAreaDOM.setText(salida);

    }//GEN-LAST:event_jButtonMostrarDOMActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        if (gesDom.añadirDOM(this.jTextFieldTitulo.getText(), this.jTextFieldAutor.getText(), this.jTextFieldPublicado.getText()) == -1) {
            this.jLabelMensaje.setText("Error al añadir el nodo");
        } else {
            this.jLabelMensaje.setText("Nodo añadido correctamente");
        }
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        if (gesDom.guardarDOMcomoFILE() == -1) {
            this.jLabelMensaje.setText("Error al guardar el fichero");
        } else {
            this.jLabelMensaje.setText("Fichero guardado correctamente");
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTituloActionPerformed

        gesDom.modificarDOMparaTituloLibro(jTextFieldTituloAntiguo.getText(), jTextFieldTituloNuevo.getText());
        jLabelMensaje.setText("Titulo Modificado con Exito");

    }//GEN-LAST:event_jButtonModificarTituloActionPerformed

    private void jButtonMostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarSAXActionPerformed
        String salida = gesSAX.recorrerSAX();
        this.jTextAreaDOM.setText(salida);
    }//GEN-LAST:event_jButtonMostrarSAXActionPerformed

    private void jAbrirSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirSAXActionPerformed
        File ficheroXML;
        ficheroXML = dialogoSeleccionarFichero();

        if (ficheroXML == null) {
            jLabelMensaje.setText("Vuelve a seleccionar el fichero.");
        } else {
            if (gesSAX.abrir_XML_SAX(ficheroXML) == -1) {
                this.jLabelMensaje.setText("Error al crear el objeto SAX.");
                this.jButtonMostrarDOM.setEnabled(false);
                this.jButtonAñadir.setEnabled(false);
                this.jButtonGuardar.setEnabled(false);
                this.jButtonModificarTitulo.setEnabled(false);
                this.jButtonMostrarSAX.setEnabled(false);
                this.jButtonMostrarJAXB.setEnabled(false);
            } else {
                this.jLabelMensaje.setText("Ya se ha abierto el archivo para SAX.");
                this.jButtonMostrarDOM.setEnabled(false);
                this.jButtonAñadir.setEnabled(false);
                this.jButtonGuardar.setEnabled(false);
                this.jButtonModificarTitulo.setEnabled(true);
                this.jButtonMostrarSAX.setEnabled(true);
                this.jButtonMostrarJAXB.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jAbrirSAXActionPerformed

    private void jAbrirJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirJAXBActionPerformed

        File ficheroXML;
        ficheroXML = dialogoSeleccionarFichero();

        if (ficheroXML == null) {
            jLabelMensaje.setText("Vuelve a seleccionar el fichero.");
        } else {
            if (gesJAXB.abrir_XML_JAXB(ficheroXML) == -1) {
                this.jLabelMensaje.setText("Error al crear el objeto JAXB.");
                this.jButtonMostrarDOM.setEnabled(false);
                this.jButtonAñadir.setEnabled(false);
                this.jButtonGuardar.setEnabled(false);
                this.jButtonModificarTitulo.setEnabled(false);
                this.jButtonMostrarSAX.setEnabled(false);
                this.jButtonMostrarJAXB.setEnabled(false);

            } else {
                this.jLabelMensaje.setText("Ya se ha abierto el archivo para JAXB.");
                this.jButtonMostrarDOM.setEnabled(false);
                this.jButtonAñadir.setEnabled(false);
                this.jButtonGuardar.setEnabled(false);
                this.jButtonModificarTitulo.setEnabled(false);
                this.jButtonMostrarSAX.setEnabled(false);
                this.jButtonMostrarJAXB.setEnabled(true);
            }
        }


    }//GEN-LAST:event_jAbrirJAXBActionPerformed

    private void jButtonMostrarJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarJAXBActionPerformed
        String salida = gesJAXB.recorrerJAXB();
        this.jTextAreaDOM.setText(salida);
    }//GEN-LAST:event_jButtonMostrarJAXBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAbrirDOM;
    private javax.swing.JMenuItem jAbrirJAXB;
    private javax.swing.JMenuItem jAbrirSAX;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificarTitulo;
    private javax.swing.JButton jButtonMostrarDOM;
    private javax.swing.JButton jButtonMostrarJAXB;
    private javax.swing.JButton jButtonMostrarSAX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDOM;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldPublicado;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldTituloAntiguo;
    private javax.swing.JTextField jTextFieldTituloNuevo;
    // End of variables declaration//GEN-END:variables

    private File dialogoSeleccionarFichero() {
        File fichero = null;

        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        int rv = fc.showOpenDialog(this);
        if (rv == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
        }
        return fichero;
    }
}
